name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to EC2 and pull latest & restart
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ec2-13-204-80-216.ap-south-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/myciapp
            ./deploy.sh
            # cd /home/ubuntu/myciapp
            # git fetch origin
            # git reset --hard origin/main
            # sudo systemctl restart yourapp
